FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install 
ENV NODE_ENV=production
COPY . .
RUN npm run build


ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

EXPOSE 8080

CMD ["npm", "start"]

