FROM node:20

WORKDIR /app

COPY package*.json ./
RUN RUN npm ci

COPY . .
ENV NODE_ENV=production
RUN npm run build

EXPOSE 8080

ENV PORT=8080
ENV NODE_ENV=production

CMD ["npx", "next", "start", "-p", "8080"]

