FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

COPY package.json package-lock.json* ./
RUN npm install --no-audit --prefer-offline --no-fund

COPY . .
RUN npm run build

EXPOSE 8080

CMD ["npm", "start"]

