
import { Club, ClubStatus, PricingPlan } from '../types';

export const INITIAL_CLUBS: Club[] = [
  {
    id: "1",
    name: "Padel Social Club - Earls Court",
    categories: ["Padel Club", "Sports Bar"],
    street_address: "Empress Place",
    full_address: "Empress Place, London SW6 1TT, UK",
    city: "London",
    region: "Greater London",
    postcode: "SW6 1TT",
    country: "United Kingdom",
    country_code: "GB",
    phone: "+44 20 1234 5678",
    website: "https://padelsocialclub.com",
    maps_url: "https://goo.gl/maps/example1",
    booking_url: "https://playtomic.io/example1",
    lat: 51.4883,
    lng: -0.1912,
    rating: 4.8,
    rating_count: 124,
    opening_hours_raw: "Mon-Sun: 7am-11pm",
    image_url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800",
    slug: "padel-social-club-earls-court-london",
    status: ClubStatus.CLAIMED,
    owner_user_id: "user_1",
    is_featured: true,
    plan: PricingPlan.PARTNER
  },
  {
    id: "2",
    name: "Stratford Padel Club",
    categories: ["Padel Club"],
    street_address: "221 Bermondsey St",
    full_address: "221 Bermondsey St, London SE1 3XW, UK",
    city: "London",
    region: "Greater London",
    postcode: "SE1 3XW",
    country: "United Kingdom",
    country_code: "GB",
    phone: "+44 20 7654 3210",
    website: "https://stratfordpadelclub.org",
    maps_url: "https://goo.gl/maps/example2",
    booking_url: "https://stratfordpadelclub.org/book",
    lat: 51.5414,
    lng: -0.0034,
    rating: 4.5,
    rating_count: 312,
    opening_hours_raw: "Mon-Fri: 6am-10pm, Sat-Sun: 8am-8pm",
    image_url: "https://images.unsplash.com/photo-1599474924187-334a4ae5bd3c?auto=format&fit=crop&q=80&w=800",
    slug: "stratford-padel-club-london",
    status: ClubStatus.UNCLAIMED,
    owner_user_id: null,
    is_featured: false,
    plan: PricingPlan.FREE
  },
  {
    id: "3",
    name: "Padel United - Manchester",
    categories: ["Sports Club", "Padel Club"],
    street_address: "Manchester Way",
    full_address: "Manchester Way, Manchester M1 1AA, UK",
    city: "Manchester",
    region: "Greater Manchester",
    postcode: "M1 1AA",
    country: "United Kingdom",
    country_code: "GB",
    phone: "+44 161 123 4567",
    website: "https://padeluniteduk.com",
    maps_url: "https://goo.gl/maps/example3",
    booking_url: "https://playtomic.io/manchester",
    lat: 53.4808,
    lng: -2.2426,
    rating: 4.7,
    rating_count: 89,
    opening_hours_raw: "Daily 8am-10pm",
    image_url: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&q=80&w=800",
    slug: "padel-united-manchester",
    status: ClubStatus.CLAIMED,
    owner_user_id: "user_2",
    is_featured: true,
    plan: PricingPlan.FEATURED
  },
  {
    id: "4",
    name: "Bristol Padel Centre",
    categories: ["Padel Club"],
    street_address: "Court Road",
    full_address: "Court Road, Bristol BS1 2BB, UK",
    city: "Bristol",
    region: "Bristol",
    postcode: "BS1 2BB",
    country: "United Kingdom",
    country_code: "GB",
    phone: null,
    website: "https://bristolpadel.co.uk",
    maps_url: null,
    booking_url: null,
    lat: 51.4545,
    lng: -2.5879,
    rating: 4.2,
    rating_count: 45,
    opening_hours_raw: "Mon-Sun: 9am-9pm",
    image_url: "https://images.unsplash.com/photo-1541534741688-6078c64b5cc5?auto=format&fit=crop&q=80&w=800",
    slug: "bristol-padel-centre-bristol",
    status: ClubStatus.UNCLAIMED,
    owner_user_id: null,
    is_featured: false,
    plan: PricingPlan.FREE
  },
  {
    id: "5",
    name: "Birmingham Padel",
    categories: ["Padel Club", "Tennis Club"],
    street_address: "Brum St",
    full_address: "Brum St, Birmingham B1 1BB, UK",
    city: "Birmingham",
    region: "West Midlands",
    postcode: "B1 1BB",
    country: "United Kingdom",
    country_code: "GB",
    phone: "+44 121 555 1234",
    website: "https://birminghampadel.com",
    maps_url: null,
    booking_url: "https://birminghampadel.com/book",
    lat: 52.4862,
    lng: -1.8904,
    rating: 3.9,
    rating_count: 22,
    opening_hours_raw: "Mon-Sun: 8am-10pm",
    image_url: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=800",
    slug: "birmingham-padel-birmingham",
    status: ClubStatus.UNCLAIMED,
    owner_user_id: null,
    is_featured: false,
    plan: PricingPlan.FREE
  }
];
